"""add name in netmap

Revision ID: a23f29d020c3
Revises: b4dfb15bee30
Create Date: 2023-09-01 13:44:36.701418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a23f29d020c3'
down_revision: Union[str, None] = 'b4dfb15bee30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('netmap', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('netmap', 'name')
    # ### end Alembic commands ###
