"""add node modelss

Revision ID: b4dfb15bee30
Revises: d46c14b833d6
Create Date: 2023-09-01 13:14:35.428185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4dfb15bee30'
down_revision: Union[str, None] = 'd46c14b833d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('netmap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hostname', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('mac', sa.String(), nullable=True),
    sa.Column('uplink', sa.Integer(), nullable=True),
    sa.Column('ro_community', sa.String(), nullable=True),
    sa.Column('rw_community', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('netmap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['netmap_id'], ['netmap.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('target_port', sa.Integer(), nullable=False),
    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('netmap_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['netmap_id'], ['netmap.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    op.drop_table('node')
    op.drop_table('netmap')
    # ### end Alembic commands ###
